pub mod app;
pub mod backend;
pub mod benchmark;
pub mod cache;
pub mod contract;
pub mod contract_build;
pub mod dependencies;
pub mod database;
pub mod database_runtime;
pub mod database_sqlite;
pub mod database_fleet;
pub mod deploy;
pub mod diff;
pub mod doctor;
pub mod editor;
pub mod editor_workflows;
pub mod domain;
pub mod extensions;
pub mod init;
pub mod inspector;
mod inspector_dashboard;
mod inspector_frontend;
mod inspector_jev;
mod inspector_runtime;
mod inspector_server;
pub mod install;
pub mod lsp;
pub mod join;
mod legacy_mock;
pub mod mock;
mod mock_development;
pub mod onboard;
pub mod packages;
pub mod project; // Add this
pub mod pull;
pub mod release;
pub mod run;
pub mod security;
pub mod scenario;
pub mod serve;
pub mod server;
#[allow(dead_code)] // Standalone mock CLI types remain reserved for their execution phase.
pub(crate) mod server_command_contract;
mod server_development;
mod server_workflow;
pub mod test;
pub mod ui;
pub mod watch;

#[cfg(test)]
mod editor_schema_parity;
