// @generated by axiom-ui-host/scripts/generate_frontend_toolchain.py; do not edit.
const LYNX_ENGINE_SOURCE: &str = "https://github.com/lynx-family/lynx.git";
const LYNX_ENGINE_COMMIT: &str = "73bf89185547d0caf725bab4f3a46fa1e1f9616d";
const LYNX_UI_VERSION: &str = "3.138.0";
const LYNX_UI_SOURCE_COMMIT: &str = "b9b3fd7a34d7cde6ef4dddfb2fb95de4f5457d73";
const LYNX_UI_NPM_INTEGRITY: &str = "sha512-7j1au6sOIHY+lHnM1iR5UcevSPxOzwGM7mbB1H8s3cZeTgWcrnbPgCoPToetjc2vJ6jymk/+hlduXcOlrDHL/A==";
const FRONTEND_TOOLCHAIN_ID: &str = "sha256:a5b06beb920420f7f9e4676ae5ccdcdf897336601272174b9e8f8badfed85d58";
const LYNX_BUNDLE_ENGINE_VERSION: &str = "3.2";
const FRONTEND_PACKAGES: &[(&str, &str, &str)] = &[
    ("@lynx-js/lynx-ui", "3.138.0", "sha512-7j1au6sOIHY+lHnM1iR5UcevSPxOzwGM7mbB1H8s3cZeTgWcrnbPgCoPToetjc2vJ6jymk/+hlduXcOlrDHL/A=="),
    ("@lynx-js/lynx-ui-overlay", "3.137.0", "sha512-iTQEkT4K6KOTKBYjWipzcHaN6vthasRzNCaDwUcRMlwGU7n7SqIr11aviQuG0wQwWRM1nFOBpEv6DD3O5oCG0g=="),
    ("@lynx-js/react", "0.123.1", "sha512-wgkSly8Nv3O6tdWJ5tc+dgUHp+XpPzJdOy36dPA1np9LXUEWfwkiWs6BBkluPv620c6tyev2Vj3cEjnGHs0orw=="),
    ("@lynx-js/react-rsbuild-plugin", "0.18.1", "sha512-c+ekAagAocry6NjQMIyn67CN++fU8pStM+9khWfM2ioL/j4zL0jePiuV49gBvLBCErayOrMRB2+/IrokhnIBkw=="),
    ("@lynx-js/rspeedy", "0.16.1", "sha512-E8FVmglBIfpyZ7AuBlB4Nl+H99uO5F+Hx35HHYW7ySuB/gFxh2+JNx9z5ll1CvfK76ePQmVdsB99ZnVobBPV1w=="),
    ("@lynx-js/types", "4.1.0", "sha512-WLWnMpGZMrjffSR62PYesSfjD0RWumPyT21iMTi7GySGkOSOGdv4q4wWkarg8zNI7SxcCFM6kpXFhyIERADBPQ=="),
    ("@types/react", "18.3.28", "sha512-z9VXpC7MWrhfWipitjNdgCauoMLRdIILQsAEV+ZesIzBq/oUlxk0m3ApZuMFCXdnS4U7KrI+l3WRUEGQ8K1QKw=="),
    ("typescript", "5.8.3", "sha512-p1diW6TqL9L07nNxvRMM7hMMw4c5XOo/1ibL4aAIGmSAt9slTE1Xgw5KWuof2uTOvCg9BY7ZRi+GaF+7sfgPeQ=="),
];
const FRONTEND_PACKAGE_JSON: &str = include_str!("../../../../axiom-ui-host/toolchain/npm/package.json");
const FRONTEND_PACKAGE_LOCK: &str = include_str!("../../../../axiom-ui-host/toolchain/npm/package-lock.json");
const FRONTEND_PACKAGE_LOCK_SHA256: &str = "799c2cd3779790f1d0b26fbb1396717c2e69f5ea4bd0485284038965818165b0";
